/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentesRouteImport } from './routes/ventes'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as TransfertsRouteImport } from './routes/transferts'
import { Route as StockRouteImport } from './routes/stock'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as MagasinsRouteImport } from './routes/magasins'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventaireRouteImport } from './routes/inventaire'
import { Route as FournisseursRouteImport } from './routes/fournisseurs'
import { Route as FacturesFournisseursRouteImport } from './routes/factures-fournisseurs'
import { Route as DettesRouteImport } from './routes/dettes'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CaisseRouteImport } from './routes/caisse'
import { Route as AchatsRouteImport } from './routes/achats'
import { Route as IndexRouteImport } from './routes/index'

const VentesRoute = VentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfertsRoute = TransfertsRouteImport.update({
  id: '/transferts',
  path: '/transferts',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const MagasinsRoute = MagasinsRouteImport.update({
  id: '/magasins',
  path: '/magasins',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventaireRoute = InventaireRouteImport.update({
  id: '/inventaire',
  path: '/inventaire',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursRoute = FournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesFournisseursRoute = FacturesFournisseursRouteImport.update({
  id: '/factures-fournisseurs',
  path: '/factures-fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const DettesRoute = DettesRouteImport.update({
  id: '/dettes',
  path: '/dettes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CaisseRoute = CaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => rootRouteImport,
} as any)
const AchatsRoute = AchatsRouteImport.update({
  id: '/achats',
  path: '/achats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achats': typeof AchatsRoute
  '/caisse': typeof CaisseRoute
  '/categories': typeof CategoriesRoute
  '/clients': typeof ClientsRoute
  '/dettes': typeof DettesRoute
  '/factures-fournisseurs': typeof FacturesFournisseursRoute
  '/fournisseurs': typeof FournisseursRoute
  '/inventaire': typeof InventaireRoute
  '/login': typeof LoginRoute
  '/magasins': typeof MagasinsRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/rapports': typeof RapportsRoute
  '/stock': typeof StockRoute
  '/transferts': typeof TransfertsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/ventes': typeof VentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achats': typeof AchatsRoute
  '/caisse': typeof CaisseRoute
  '/categories': typeof CategoriesRoute
  '/clients': typeof ClientsRoute
  '/dettes': typeof DettesRoute
  '/factures-fournisseurs': typeof FacturesFournisseursRoute
  '/fournisseurs': typeof FournisseursRoute
  '/inventaire': typeof InventaireRoute
  '/login': typeof LoginRoute
  '/magasins': typeof MagasinsRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/rapports': typeof RapportsRoute
  '/stock': typeof StockRoute
  '/transferts': typeof TransfertsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/ventes': typeof VentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achats': typeof AchatsRoute
  '/caisse': typeof CaisseRoute
  '/categories': typeof CategoriesRoute
  '/clients': typeof ClientsRoute
  '/dettes': typeof DettesRoute
  '/factures-fournisseurs': typeof FacturesFournisseursRoute
  '/fournisseurs': typeof FournisseursRoute
  '/inventaire': typeof InventaireRoute
  '/login': typeof LoginRoute
  '/magasins': typeof MagasinsRoute
  '/parametres': typeof ParametresRoute
  '/produits': typeof ProduitsRoute
  '/rapports': typeof RapportsRoute
  '/stock': typeof StockRoute
  '/transferts': typeof TransfertsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/ventes': typeof VentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achats'
    | '/caisse'
    | '/categories'
    | '/clients'
    | '/dettes'
    | '/factures-fournisseurs'
    | '/fournisseurs'
    | '/inventaire'
    | '/login'
    | '/magasins'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/stock'
    | '/transferts'
    | '/utilisateurs'
    | '/ventes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achats'
    | '/caisse'
    | '/categories'
    | '/clients'
    | '/dettes'
    | '/factures-fournisseurs'
    | '/fournisseurs'
    | '/inventaire'
    | '/login'
    | '/magasins'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/stock'
    | '/transferts'
    | '/utilisateurs'
    | '/ventes'
  id:
    | '__root__'
    | '/'
    | '/achats'
    | '/caisse'
    | '/categories'
    | '/clients'
    | '/dettes'
    | '/factures-fournisseurs'
    | '/fournisseurs'
    | '/inventaire'
    | '/login'
    | '/magasins'
    | '/parametres'
    | '/produits'
    | '/rapports'
    | '/stock'
    | '/transferts'
    | '/utilisateurs'
    | '/ventes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchatsRoute: typeof AchatsRoute
  CaisseRoute: typeof CaisseRoute
  CategoriesRoute: typeof CategoriesRoute
  ClientsRoute: typeof ClientsRoute
  DettesRoute: typeof DettesRoute
  FacturesFournisseursRoute: typeof FacturesFournisseursRoute
  FournisseursRoute: typeof FournisseursRoute
  InventaireRoute: typeof InventaireRoute
  LoginRoute: typeof LoginRoute
  MagasinsRoute: typeof MagasinsRoute
  ParametresRoute: typeof ParametresRoute
  ProduitsRoute: typeof ProduitsRoute
  RapportsRoute: typeof RapportsRoute
  StockRoute: typeof StockRoute
  TransfertsRoute: typeof TransfertsRoute
  UtilisateursRoute: typeof UtilisateursRoute
  VentesRoute: typeof VentesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventes': {
      id: '/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof VentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferts': {
      id: '/transferts'
      path: '/transferts'
      fullPath: '/transferts'
      preLoaderRoute: typeof TransfertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magasins': {
      id: '/magasins'
      path: '/magasins'
      fullPath: '/magasins'
      preLoaderRoute: typeof MagasinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventaire': {
      id: '/inventaire'
      path: '/inventaire'
      fullPath: '/inventaire'
      preLoaderRoute: typeof InventaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs': {
      id: '/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof FournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures-fournisseurs': {
      id: '/factures-fournisseurs'
      path: '/factures-fournisseurs'
      fullPath: '/factures-fournisseurs'
      preLoaderRoute: typeof FacturesFournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dettes': {
      id: '/dettes'
      path: '/dettes'
      fullPath: '/dettes'
      preLoaderRoute: typeof DettesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caisse': {
      id: '/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof CaisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achats': {
      id: '/achats'
      path: '/achats'
      fullPath: '/achats'
      preLoaderRoute: typeof AchatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchatsRoute: AchatsRoute,
  CaisseRoute: CaisseRoute,
  CategoriesRoute: CategoriesRoute,
  ClientsRoute: ClientsRoute,
  DettesRoute: DettesRoute,
  FacturesFournisseursRoute: FacturesFournisseursRoute,
  FournisseursRoute: FournisseursRoute,
  InventaireRoute: InventaireRoute,
  LoginRoute: LoginRoute,
  MagasinsRoute: MagasinsRoute,
  ParametresRoute: ParametresRoute,
  ProduitsRoute: ProduitsRoute,
  RapportsRoute: RapportsRoute,
  StockRoute: StockRoute,
  TransfertsRoute: TransfertsRoute,
  UtilisateursRoute: UtilisateursRoute,
  VentesRoute: VentesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
